const projects={
ALADIN:{name:'ALADIN',type:'RESIDENTIAL DEVELOPMENT',desc:'Энергоэффективные малоэтажные дома и таунхаусы нового поколения.',tags:['PILOT','~70 М²','4 СЕКЦИИ','ENERGY'],capex:11.02,revenue:16.8,ebitda:5.78,roi:52.5,payback:'~18 мес.',image:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85',accent:'gold',hero:'Дом, созданный для жизни',investor:'Инвестору нужен понятный актив, контролируемые этапы и прозрачная экономика.',team:'Команде нужен реальный проект, на котором можно вырасти вместе с компанией.',buyer:'Покупателю нужен собственный дом, комфорт, безопасность и предсказуемые расходы.',features:['Современная архитектура','Энергоэффективность','Собственная территория','Парковка','Полный цикл'],numbers:['~70 м²','4 секции','до 12 мес.','20% целевая договорная доходность*']},
'NEXUS WORK':{name:'NEXUS WORK',type:'COMMERCIAL DEVELOPMENT',desc:'Гибкий бизнес-хаб: офисы, coworking, переговорные и сервисы для компаний.',tags:['2 500 М²','OFFICES','COWORKING','SERVICES'],capex:108.5,revenue:145.5,ebitda:37,roi:34.1,payback:'~3.0 года',image:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=85',accent:'blue',hero:'Рабочая среда нового поколения',investor:'Коммерческий актив с диверсифицированным арендным продуктом и потенциалом капитализации.',team:'Проект для архитекторов, инженеров, коммерсантов и управляющих, которые хотят создавать новый стандарт рабочих пространств.',buyer:'Для компаний и специалистов — гибкая среда, где офис, сервис и деловые связи работают вместе.',features:['Гибкие площади','Coworking','Переговорные','Retail & services','Управляемый актив'],numbers:['2 500 м²','несколько форматов','арендный доход','операционный сервис']},
'CARPATHIA ECO LODGE':{name:'CARPATHIA ECO LODGE',type:'HOSPITALITY DEVELOPMENT',desc:'Природный lodge-комплекс с wellness, food и повторяющейся гостиничной выручкой.',tags:['20 LODGES','ECO','SPA','HOSPITALITY'],capex:60,revenue:21.9,ebitda:7.7,roi:12.8,payback:'~7.8 года',image:'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1600&q=85',accent:'forest',hero:'Карпаты как destination',investor:'Гостиничный актив с несколькими потоками выручки: проживание, wellness, food и experiences.',team:'Место, где архитектура, hospitality, digital-маркетинг и операционное управление становятся одним продуктом.',buyer:'Для гостя — тишина, природа, качественный сервис и современный формат отдыха.',features:['20 lodge-юнитов','Wellness','Food concept','Nature experiences','Digital booking'],numbers:['20 lodge-юнитов','wellness + food','сезонный + событийный спрос','операционная модель']},
AGROHUB:{name:'AGROHUB',type:'AGRI-INFRASTRUCTURE',desc:'Хранение, холодовая цепь, переработка, упаковка и логистика для агропроизводителей.',tags:['STORAGE','COLD CHAIN','PROCESSING','LOGISTICS'],capex:85,revenue:39.8,ebitda:13.9,roi:16.4,payback:'~6.1 года',image:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=85',accent:'agro',hero:'Инфраструктура, которая сохраняет урожай',investor:'Инфраструктурный актив с доходом от хранения, обработки, упаковки и логистики.',team:'Проект для инженеров, технологов, логистов, агрономов и операционных руководителей.',buyer:'Для производителя — меньше потерь, доступ к хранению и переработке, удобнее логистика и рынок.',features:['Складирование','Cold chain','Processing','Packaging','Logistics'],numbers:['storage','cold chain','processing','logistics']},
'ENERGY PARK':{name:'ENERGY PARK',type:'ENERGY + INDUSTRIAL DEVELOPMENT',desc:'Промышленно-коммерческий кластер с solar generation и энергетической инфраструктурой.',tags:['5 MW','INDUSTRIAL','SOLAR','ENERGY'],capex:130,revenue:55.75,ebitda:33.45,roi:25.7,payback:'~4.0 года',image:'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=1600&q=85',accent:'energy',hero:'Энергия как инфраструктурный актив',investor:'Сочетание industrial real estate и энергетической инфраструктуры с несколькими источниками ценности.',team:'Междисциплинарный проект для инженеров, энергетиков, девелоперов и специалистов по промышленным объектам.',buyer:'Для бизнеса — площадка, инфраструктура и энергоэффективность как часть долгосрочной операционной модели.',features:['Solar generation','Industrial plots','Grid infrastructure','Energy management','Commercial services'],numbers:['5 MW concept','industrial','solar','energy infrastructure']}
};
let current='ALADIN',scenario='base',slide=0,persona='investor';
const grid=document.getElementById('portfolioGrid'),tabs=document.getElementById('projectTabs'),dash=document.getElementById('dashboard');
const modal=document.getElementById('projectModal'),modalContent=document.getElementById('modalContent');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderPortfolio(){grid.innerHTML=Object.values(projects).map((p,i)=>`<article class="project-card" style="--bg:url('${p.image}')"><div class="project-img"></div><div class="project-overlay"></div><div class="project-copy"><span class="num">PROJECT ${String(i+1).padStart(2,'0')}</span><div class="type">${p.type}</div><h3>${p.name}</h3><p>${p.desc}</p><div class="tags">${p.tags.map(x=>`<span>${x}</span>`).join('')}</div><button class="open-project" data-project="${esc(p.name)}">Открыть проект ↗</button></div></article>`).join('')}
function renderTabs(){tabs.innerHTML=Object.keys(projects).map(k=>`<button class="${k===current?'active':''}" data-project="${esc(k)}">${projects[k].name}</button>`).join('')}
function adjusted(p){const c=scenario==='conservative',o=scenario==='optimistic',m=c?.82:o?1.18:1;return{capex:p.capex*(c?.95:o?1.06:1),revenue:p.revenue*m,ebitda:p.ebitda*m,roi:p.roi*(c?.75:o?1.2:1)}}
function renderDash(){const p=projects[current],a=adjusted(p);dash.innerHTML=`<div><div class="dash-title"><div><span>SELECTED MODEL</span><h3>${p.name}</h3></div><span>${p.type}</span></div><div class="metrics"><div class="metric"><small>CAPEX</small><b>₴${a.capex.toFixed(1)}M</b></div><div class="metric"><small>REVENUE / VALUE</small><b>₴${a.revenue.toFixed(1)}M</b></div><div class="metric"><small>EBITDA / RESULT</small><b>₴${a.ebitda.toFixed(1)}M</b></div><div class="metric"><small>INDICATIVE ROI</small><b>${a.roi.toFixed(1)}%</b></div><div class="metric"><small>PAYBACK</small><b>${p.payback}</b></div><div class="metric"><small>STATUS</small><b>CONCEPT</b></div></div></div><div class="chart"><div class="chart-label">ILLUSTRATIVE VALUE CURVE / ${scenario.toUpperCase()}</div><div class="chart-line"></div><div class="chart-caption">Сценарий изменяет модельные показатели для сравнения, а не прогнозирует фактический результат.</div></div>`}
const presentation={investor:{label:'ИНВЕСТОР',emotion:'УВЕРЕННОСТЬ',question:'Почему капитал должен работать здесь?',slides:(p,a)=>[
['01','THESIS',p.hero,`Структурированный ${p.type.toLowerCase()} с понятным продуктом, экономикой и маршрутом масштабирования.`],
['02','ПРОБЛЕМА','Рынок фрагментирован',`Клиентам и капиталу сложно пройти путь от идеи до готового актива без единой управляющей системы.`],
['03','ОТВЕТ','MMW DEVELOPMENT SYSTEM','LAND → CONCEPT → ECONOMICS → CAPITAL → DESIGN → BUILD → ASSET'],
['04','ПРОДУКТ',p.name,p.features.join(' • ')],
['05','РЫНОЧНАЯ ЛОГИКА','Кому нужен актив',p.buyer],
['06','ЭКОНОМИКА','Модель проекта',`CAPEX ₴${a.capex.toFixed(1)}M • VALUE/REVENUE ₴${a.revenue.toFixed(1)}M • RESULT ₴${a.ebitda.toFixed(1)}M • ROI ${a.roi.toFixed(1)}%*`],
['07','ДРАЙВЕРЫ ЦЕННОСТИ','Что создаёт маржу','Рациональный продукт • контроль CAPEX • повторяемые решения • управление продажами • операционная эффективность'],
['08','КАПИТАЛ','Как работает финансирование','Средства → согласованные этапы → контроль результата → следующий транш → реализация → возврат/доход по договорной структуре.'],
['09','КОНТРОЛЬ','Риск не прячется — он управляется','Due diligence • смета • этапность • технический контроль • юридическая структура • отчётность'],
['10','МАСШТАБ','Один проект → платформа',`Первый объект формирует стандарт. Стандарт переносится на следующие площадки, регионы и продуктовые форматы.`],
['11','ROADMAP','От concept к asset','CONCEPT → VALIDATION → LAND → CAPITAL → BUILD → SALES/OPERATIONS → REPLICATION'],
['12','DECISION','Следующий шаг',`Запросить investment memorandum, data room и индивидуальную финансово-юридическую структуру проекта.`]
]},team:{label:'КОМАНДА',emotion:'АМБИЦИЯ',question:'Почему я хочу строить эту компанию вместе с вами?',slides:(p)=>[
['01','MISSION',`СТРОИТЬ НЕ ТОЛЬКО ОБЪЕКТЫ`,`Мы создаём проектную платформу, в которой специалист видит весь путь от идеи до работающего актива.`],
['02','CHALLENGE','Рынку нужны системные команды','Архитектура, инженерия, сметы, стройка, продажи и управление должны работать как единый организм.'],
['03','YOUR ROLE','Твоя профессия влияет на продукт',p.features.join(' • ')],
['04','PROJECT','Реальный объект вместо учебного макета',p.desc],
['05','WORKFLOW','От идеи до результата','Идея → проект → экономика → земля → финансирование → строительство → продажа → актив'],
['06','GROWTH','Точка роста','Стажёр → специалист → lead → руководитель направления → руководитель проекта → партнёр'],
['07','PARTNERSHIP','Работа может стать бизнесом','На стартовых проектах возможны бонусы, project premium и партнёрские модели — только на документально согласованных условиях.'],
['08','CULTURE','FIRMITAS • UTILITAS • VENUSTAS','Прочность. Польза. Красота. Не три слова — критерии принятия проектных решений.'],
['09','DIGITAL','Работаем в единой системе','BIM • CRM • ERP • FINANCE • DOCUMENT FLOW • PROCUREMENT • SALES • ANALYTICS'],
['10','SCALE','После первого объекта','Региональная серия → новые регионы → типовые решения → проекты восстановления и инфраструктуры.'],
['11','WHO WE NEED','Кого ищем','Архитекторы • конструкторы • инженеры • сметчики • BIM/3D • PM • procurement • sales • operations'],
['12','JOIN','Как войти в команду','Профиль → портфолио/пример работы → короткое интервью → практическая задача → проектная команда.']
]},buyer:{label:'КЛИЕНТ',emotion:'ЖЕЛАНИЕ',question:'Почему я хочу выбрать именно этот продукт?',slides:(p)=>[
['01','PROMISE',p.hero,p.desc],
['02','LIFESTYLE','Больше, чем квадратные метры',p.buyer],
['03','PRODUCT','Что получает клиент',p.features.join(' • ')],
['04','SPACE','Пространство под сценарий жизни','Удобные зоны • естественный свет • приватность • рабочее пространство • место для семьи/гостей'],
['05','TECH','Технологии работают на комфорт','Проектирование → энергоэффективные решения → инженерия → качественные материалы → контроль строительства'],
['06','ECONOMY','Экономия начинается до строительства','Рациональная архитектура и энергоэффективность помогают снижать лишние площади, теплопотери и эксплуатационные расходы.'],
['07','LOCATION','Локация — часть продукта','Доступность • инфраструктура • природа/деловая среда • транспорт • потенциал развития территории'],
['08','SAFETY','Безопасность и контроль','Понятные этапы, технический контроль, документирование работ и сервис после передачи объекта.'],
['09','SERVICE','Один проект — одна команда','Архитектура • инженерия • строительство • контроль • передача • гарантийное сопровождение'],
['10','FINANCE','Покупка должна быть понятной','Собственные средства, банковские и иные законные инструменты — в зависимости от объекта и соответствия требованиям программы.'],
['11','CHOICE','Почему именно этот проект',`Продукт: ${p.name} • Формат: ${p.type} • Ключ: ${p.features.slice(0,3).join(' / ')}`],
['12','NEXT','Следующий шаг','Получить планировки, спецификацию, актуальную цену, сроки и условия бронирования по конкретному объекту.']
]}};
function visualForSlide(p,s,i){const kinds=['image','diagram','stats','flow'];const k=kinds[i%kinds.length];if(k==='image')return `<div class="slide-visual image-visual" style="background-image:linear-gradient(90deg,rgba(4,7,9,.72),rgba(4,7,9,.12)),url('${p.image}')"></div>`;if(k==='stats')return `<div class="slide-visual stats-visual"><b>${p.numbers[i%p.numbers.length]}</b><b>${p.features[(i+1)%p.features.length]}</b><b>${p.tags[(i+2)%p.tags.length]}</b></div>`;if(k==='flow')return `<div class="slide-visual flow-visual"><span>INPUT</span><i>→</i><span>MODEL</span><i>→</i><span>EXECUTION</span><i>→</i><span>ASSET</span></div>`;return `<div class="slide-visual diagram-visual"><div class="diagram-ring">${String(i+1).padStart(2,'0')}</div><div class="diagram-lines"><i></i><i></i><i></i><i></i></div></div>`}
function openProject(key){current=key;persona='investor';slide=0;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');renderModal()}
function renderModal(){const p=projects[current],pack=presentation[persona],slides=pack.slides(p,adjusted(p)),s=slides[slide];modalContent.innerHTML=`<div class="modal-kicker"><span>${p.name}</span><span>${pack.label} • ${pack.emotion}</span></div><div class="modal-head"><div><div class="eyebrow">${s[0]} / ${s[1]}</div><h2>${s[2]}</h2><p class="modal-question">${pack.question}</p></div><div class="modal-project-image" style="background-image:url('${p.image}')"></div></div><div class="slide-body"><div class="slide-copy"><p>${s[3]}</p><div class="slide-points">${p.features.slice(0,4).map((x,j)=>`<span><b>0${j+1}</b>${x}</span>`).join('')}</div></div>${visualForSlide(p,s,slide)}</div><div class="presentation-nav"><button data-persona="investor" class="${persona==='investor'?'active':''}">💰 Инвестор</button><button data-persona="team" class="${persona==='team'?'active':''}">👷 Команда</button><button data-persona="buyer" class="${persona==='buyer'?'active':''}">🏡 Клиент</button><div class="slide-controls"><button data-prev ${slide===0?'disabled':''}>←</button><span>${slide+1} / ${slides.length}</span><button data-next ${slide===slides.length-1?'disabled':''}>→</button></div></div><div class="slide-progress"><i style="width:${((slide+1)/slides.length)*100}%"></i></div>`}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}

document.addEventListener('click',e=>{const project=e.target.closest('[data-project]');if(project){if(project.closest('.project-tabs')){current=project.dataset.project;renderTabs();renderDash()}else openProject(project.dataset.project)}if(e.target.matches('[data-close]'))closeModal();if(e.target.matches('[data-persona]')){persona=e.target.dataset.persona;slide=0;renderModal()}if(e.target.matches('[data-prev]')){slide--;renderModal()}if(e.target.matches('[data-next]')){slide++;renderModal()}if(e.target.dataset.order){const labels={land:'LAND ORDER: участок, назначение, ограничения, инфраструктура и потенциал.',capital:'CAPITAL ORDER: сумма, горизонт, риск-профиль и желаемая структура.',project:'PROJECT ORDER: идея, объект, стадия, команда и необходимый результат.'};const r=document.getElementById('orderResult');r.hidden=false;r.innerHTML=`<b>${labels[e.target.dataset.order]}</b><br>Следующий шаг: отправьте запрос на <a href="mailto:itimchenko00@gmail.com">itimchenko00@gmail.com</a>.`}});
modal.addEventListener('click',e=>{if(e.target===modal||e.target.classList.contains('modal-backdrop'))closeModal()});document.addEventListener('keydown',e=>{if(!modal.classList.contains('open'))return;if(e.key==='Escape')closeModal();if(e.key==='ArrowRight'&&slide<presentation[persona].slides(projects[current]).length-1){slide++;renderModal()}if(e.key==='ArrowLeft'&&slide>0){slide--;renderModal()}});
document.querySelector('.scenario').addEventListener('click',e=>{if(e.target.dataset.s){scenario=e.target.dataset.s;document.querySelectorAll('.scenario button').forEach(b=>b.classList.toggle('active',b.dataset.s===scenario));renderDash()}});
renderPortfolio();renderTabs();renderDash();
